$(function(){
	//--
	$('.tabContentDiv').find('.tabContent:first').show();
	$('.tab').each(function(i){
		$(this).find('li').each(function(ii){
			$(this).hover(
			function(){
				$('.tab').eq(i).find('li').removeClass('liNow');
				$(this).addClass('liNow');
				$('.tabContentDiv').eq(i).find('.tabContent').hide();
				$('.tabContentDiv').eq(i).find('.tabContent').eq(ii).show();
				},
			function(){}	
				)
			})
		})
	//--
	$('.topDiv').find('.list').find('li:last').css('background','none');
	
	
	alert(33);
	
	$('.rhpPart4').find('li').hover(
	   function(){
		   $(this).addClass('liNow');
		   },
	   function(){
		   $(this).removeClass('liNow');
		   }
	)
	$('.rhpPart4').find('.rightBtn').click(function(){
		imgScrollRight2($('.rhpPart4').find('.list'),$('.rhpPart4').find('.list').find('li').length-4,225,0);
		})	
	$('.rhpPart4').find('.leftBtn').click(function(){
		imgScrollLeft2($('.rhpPart4').find('.list'),$('.rhpPart4').find('.list').find('li').length-4,225,0);
		})
	//--
	$('.rhpPart5').find('li').hover(
	   function(){
		   $(this).addClass('liNow');
		   },
	   function(){
		   $(this).removeClass('liNow');
		   }
	)
	$('.rhpPart5').find('.rightBtn').click(function(){
		alert(22);
		imgScrollRight2($('.rhpPart5').find('.list'),$('.rhpPart5').find('.list').find('li').length-5,160,1);
		})	
	$('.rhpPart5').find('.leftBtn').click(function(){
		imgScrollLeft2($('.rhpPart5').find('.list'),$('.rhpPart5').find('.list').find('li').length-5,160,1);
		})
	
	
	
	
	//--
	$('.topCartLayerA').hover(
	   function(){
		   $('.topCartLayer').show();
		   },
	   function(){
		   $('.topCartLayer').hide();
		   }
	)
	$('.topCartLayer').hover(
	   function(){
		   $(this).show();
		   },
	   function(){
		   $(this).hide();
		   }
	)
	//--
	$('.topSearch').find('div').hover(
	   function(){
		   $('.topSearchLayer').css('left',$(this).offset().left-2);
		   $('.topSearchLayer').css('top',$(this).offset().top+29);
		   $('.topSearchLayer').show();
		   },
	   function(){
		   $('.topSearchLayer').hide();
		   }
	)
	$('.topSearchLayer').hover(
	   function(){
		   $(this).show();
		   },
	   function(){
		   $(this).hide();
		   }
	)
	//--
	$('.indexFlash').hover(
	   function(){
		   $(this).find('.rightBtn').show();
		   $(this).find('.leftBtn').show();
		   },
	   function(){
		   $(this).find('.rightBtn').hide();
		   $(this).find('.leftBtn').hide();
		   }
	)
	$('.indexFlash').find('.list2').find('li:last').css('border','0px');
	$('.indexFlash').find('.list2').find('li').hover(
	   function(){
		   $(this).addClass('liNow');
		   },
	   function(){
		   $(this).removeClass('liNow');
		   }
	)
	//--
	$('.indexPart1_02').find('li').hover(
	   function(){
		   $(this).addClass('liNow');
		   $(this).find('.imgDiv').animate({top: -30}, 300);
		   $(this).find('.btn').animate({top: 75,opacity:'show'}, 300);
		   $(this).find('.contentDiv').animate({top: 89,height:112,'paddingTop':28}, 300);
		   },
	   function(){
		   $(this).removeClass('liNow');
		   $(this).find('.imgDiv').animate({top: 0}, 300);
		   $(this).find('.btn').animate({top: 105,opacity:'hide'}, 300);
		   $(this).find('.contentDiv').animate({top: 119,height:46,'paddingTop':8}, 300);
		   }
	)
	//--
	$('.indexPart3_03').find('li:last').css('border','0px');
	$('.Orders').find('tr:last').find('td').css('border','0px');
	//--
	$('.orderLayer1A').click(function(){
		$('.orderLayer').hide();
		$('.orderLayer1').css('left',$(this).offset().left-325);
		$('.orderLayer1').css('top',$(this).offset().top+12);
		$('.orderLayer1').show();
		})
	$('.orderLayer2A').click(function(){
		$('.orderLayer').hide();
		$('.orderLayer2').css('left',$(this).offset().left-440);
		$('.orderLayer2').css('top',$(this).offset().top+12);
		$('.orderLayer2').show();
		})
	$('.orderLayer3A').click(function(){
		$('.orderLayer').hide();
		$('.orderLayer3').css('left',$(this).offset().left-490);
		$('.orderLayer3').css('top',$(this).offset().top+12);
		$('.orderLayer3').show();
		})
	$('.orderLayer4A').click(function(){
		$('.orderLayer').hide();
		$('.orderLayer4').css('left',$(this).offset().left-537);
		$('.orderLayer4').css('top',$(this).offset().top+12);
		$('.orderLayer4').show();
		})
	$('.ComplaintLayerA').click(function(){
		$('.orderLayer').hide();
		$('.ComplaintLayer').css('left',$(this).offset().left-527);
		$('.ComplaintLayer').css('top',$(this).offset().top+12);
		$('.ComplaintLayer').show();
		})
	$('.ComplaintLayer2A').click(function(){
		$('.orderLayer').hide();
		$('.ComplaintLayer2').css('left',$(this).offset().left-474);
		$('.ComplaintLayer2').css('top',$(this).offset().top+32);
		$('.ComplaintLayer2').show();
		})	
	$('.trainLayerA').click(function(){
		$('.orderLayer').hide();
		$('.trainLayer').css('left',$(this).offset().left-474);
		$('.trainLayer').css('top',$(this).offset().top+32);
		$('.trainLayer').show();
		})	
	$('.trainLayer2A').click(function(){
		$('.orderLayer').hide();
		$('.trainLayer2').css('left',$(this).offset().left-330);
		$('.trainLayer2').css('top',$(this).offset().top+12);
		$('.trainLayer2').show();
		})			
	$('.orderLayer').find('.close').click(function(){
		$('.orderLayer').hide();
		})
	//--
	$('.serviceLayerA').click(function(){
		$('.pageLayer').hide();
		$('.serviceLayer').css('left',$(this).offset().left-474);
		$('.serviceLayer').css('top',$(this).offset().top+32);
		$('.serviceLayer').show();
		})
	$('.lyLayerA').click(function(){
		$('.pageLayer').hide();
		$('.lyLayer').css('left',$(this).offset().left-525);
		$('.lyLayer').css('top',$(this).offset().top+12);
		$('.lyLayer').show();
		})
	$('.orderLayer5A').hover(
	    function(){
		$('.pageLayer').hide();
		$('.orderLayer5').css('left',$(this).offset().left);
		$('.orderLayer5').css('top',$(this).offset().top+20);
		$('.orderLayer5').show();
		},
		function(){}
		)	
	$('.jjjyLayerA').click(function(){
		$('.pageLayer').hide();
		$('.jjjyLayer').css('left',$(this).offset().left-525);
		$('.jjjyLayer').css('top',$(this).offset().top+12);
		$('.jjjyLayer').show();
		})
	$('.yfpjLayerA').click(function(){
		$('.yfpjLayer').hide();
		$('.yfpjLayer').css('left',$(this).offset().left-705);
		$('.yfpjLayer').css('top',$(this).offset().top+12);
		$('.yfpjLayer').show();
		})			
	$('.coursePublish2LayerA').click(function(){
		$('.coursePublish2Layer').hide();
		$('.coursePublish2Layer').css('left',$(this).offset().left);
		$('.coursePublish2Layer').css('top',$(this).offset().top+12);
		$('.coursePublish2Layer').show();
		})		
	$('.pageLayer').find('.close').click(function(){
		$('.pageLayer').hide();
		})	
	//--
	if($('.Vertical_scroll').length>0){
		Vertical_scrollFun();
		}
	//--
	$('.course').find('.timeA').click(function(){
		$('.courseLayer1').css('left',$(this).offset().left);
		$('.courseLayer1').css('top',$(this).offset().top+16);
		//$('.courseLayer1').show();
		Vertical_scrollFun();
		})	
	//--
	$('.sideNav').find('li').each(function(i){
		$(this).find('.name').find('a').click(function(){
			$('.sideNav').find('li').find('.name').find('a').removeClass('aNow');
			$(this).addClass('aNow');
			$('.sideNav').find('li').find('.list').hide();
			$('.sideNav').find('li').eq(i).find('.list').show();
			})
		})
	//--
	$('.Orders').find('tr').find('th:last').css('border','0px');	
	$('.sideList2').find('li:last').css('background','none');	
	//--
	$('.coursePublishA').hover(
	   function(){
		   $('.coursePublishLayer').css('left',$(this).offset().left-350);
		   $('.coursePublishLayer').css('top',$(this).offset().top+30);
		   $('.coursePublishLayer').show();
		   },
	   function(){
		   $('.coursePublishLayer').hide();
		   }
	)
	$('.coursePublish2A').hover(
	   function(){
		   $('.coursePublishLayer').css('left',$(this).offset().left-350);
		   $('.coursePublishLayer').css('top',$(this).offset().top+10);
		   $('.coursePublishLayer').show();
		   },
	   function(){
		   $('.coursePublishLayer').hide();
		   }
	)
	$('.coursePublishLayer').hover(
	   function(){
		   $(this).show();
		   },
	   function(){
		   $(this).hide();
		   }
	)
	$('.recordLayerA').hover(
	   function(){
		   $('.recordLayer').css('left',$(this).offset().left+15);
		   $('.recordLayer').css('top',$(this).offset().top+10);
		   $('.recordLayer').show();
		   },
	   function(){
		   $('.recordLayer').hide();
		   }
	)	
	$('.myComplaintsLayerA').hover(
	   function(){
		   $('.myComplaintsLayer').css('left',$(this).offset().left-350);
		   $('.myComplaintsLayer').css('top',$(this).offset().top+15);
		   $('.myComplaintsLayer').show();
		   },
	   function(){
		   $('.myComplaintsLayer').hide();
		   }
	)	
	$('.pageLayer_1').find('.close').click(function(){
		$('.pageLayer_1').hide();
		})	
	//--
	$('.sNavA').each(function(i){
		$(this).hover(
		   function(){
			   $('.sNav').eq(i).show();
			   },
		   function(){
			   $('.sNav').hide();
			   }
		)
		})	
	$('.sNav').each(function(i){
		$(this).hover(
		   function(){
			   $('.sNavA').eq(i).addClass('aNow');
			   $(this).show();
			   },
		   function(){
			   $('.sNavA').removeClass('aNow');
			   $(this).hide();
			   }
		)
		})	
	//--
	var fadeFlashTime=new Array();
	$('.fadeFlash').find('li:first').fadeIn(500);
	$('.fadeFlash').each(function(i){
		fadeFlashTime[i] = setInterval("fadeFlashFun("+i+")",5000);
		$(this).find('.btnDiv').find('span').each(function(ii){
			$(this).hover(
			function(){
				clearInterval(fadeFlashTime[i]);
				$('.fadeFlash').eq(i).find('.btnDiv').find('span').removeClass('spanNow');
				$(this).addClass('spanNow');
				$('.fadeFlash').eq(i).find('li').eq(fadeFlashNow[i]).fadeOut(500);
				fadeFlashNow[i]=ii;
				$('.fadeFlash').eq(i).find('li').eq(fadeFlashNow[i]).fadeIn(500);
				fadeFlashTime[i] = setInterval("fadeFlashFun("+i+")",5000);
				},
			function(){}	
				)
			})
		$(this).find('.rightBtn').click(function(){
			clearInterval(fadeFlashTime[i]);
			$('.fadeFlash').eq(i).find('.btnDiv').find('span').removeClass('spanNow');
			$('.fadeFlash').eq(i).find('li').eq(fadeFlashNow[i]).fadeOut(500);
			if(fadeFlashNow[i]<$('.fadeFlash').eq(i).find('li').length-1){
				fadeFlashNow[i]++;
				}else{
					fadeFlashNow[i]=0;
					}
			$('.fadeFlash').eq(i).find('.btnDiv').find('span').eq(fadeFlashNow[i]).addClass('spanNow');
			$('.fadeFlash').eq(i).find('li').eq(fadeFlashNow[i]).fadeIn(500);
			fadeFlashTime[i] = setInterval("fadeFlashFun("+i+")",5000);
			})	
		$(this).find('.leftBtn').click(function(){
			clearInterval(fadeFlashTime[i]);
			$('.fadeFlash').eq(i).find('.btnDiv').find('span').removeClass('spanNow');
			$('.fadeFlash').eq(i).find('li').eq(fadeFlashNow[i]).fadeOut(500);
			if(fadeFlashNow[i]>0){
				fadeFlashNow[i]--;
				}else{
					fadeFlashNow[i]=$('.fadeFlash').eq(i).find('li').length-1;
					}
			$('.fadeFlash').eq(i).find('.btnDiv').find('span').eq(fadeFlashNow[i]).addClass('spanNow');
			$('.fadeFlash').eq(i).find('li').eq(fadeFlashNow[i]).fadeIn(500);
			fadeFlashTime[i] = setInterval("fadeFlashFun("+i+")",5000);
			})	
		})
	//--
	$('.indexPart1_03').find('.rightBtn').click(function(){
		$('.indexPart1_03').find('.list').animate({scrollTop: $('.indexPart1_03').find('.list').scrollTop()+211}, 200);
		})	
	$('.indexPart1_03').find('.leftBtn').click(function(){
		$('.indexPart1_03').find('.list').animate({scrollTop: $('.indexPart1_03').find('.list').scrollTop()-211}, 200);
		})
	//--
	$('.indexPart2_03').find('.rightBtn').click(function(){
		$('.indexPart2_03').find('.list').animate({scrollTop: $('.indexPart2_03').find('.list').scrollTop()+20}, 200);
		})	
	$('.indexPart2_03').find('.leftBtn').click(function(){
		$('.indexPart2_03').find('.list').animate({scrollTop: $('.indexPart2_03').find('.list').scrollTop()-20}, 200);
		})	
	//--
	$('.rightLayer').find('.btn').each(function(i){
		$(this).hover(
		   function(){
			   $('.rightLayer').find('.name').eq(i).animate({width: $('.rightLayer').find('.name').eq(i).find('div').width()+33}, 300);
			   $('.rightLayer').find('li').eq(i).find('.btn').find('img:first').show();
			   $('.rightLayer').find('li').eq(i).find('.btn').find('img:last').hide();
			   },
		   function(){
			   }
		)
		})
	$('.rightLayer').find('li').each(function(i){
		$(this).hover(
		   function(){
			   },
		   function(){
			   $('.rightLayer').find('.name').eq(i).animate({width: 0}, 300);
			   $('.rightLayer').find('li').eq(i).find('.btn').find('img:first').hide();
			   $('.rightLayer').find('li').eq(i).find('.btn').find('img:last').show();
			   }
		)
		})		
	//--
	$(window).scroll(function(){
			if($(window).scrollTop()>$(window).height()/2){
				$('.topA').fadeIn('slow');
				}else{
					$('.topA').fadeOut('slow');
					}
			})	
	//--
	var FreeCourseTime;
	if($('.indexPart3_02').length>0){
		$('.FreeCourseLayer').each(function(i){
			FreeCourseArray[i]=$(this).height();
			$(this).css('padding-top',$(this).height());
			$(this).height(0);
			})
		}
	$('.indexPart3_02').find('img').each(function(i){
		$(this).hover(
		   function(){
			   $('.FreeCourseLayer').hide();
			   clearTimeout(FreeCourseTime);
		       FreeCourseTime=setTimeout("FreeCourse("+i+")",100);
			   },
		   function(){
			   FreeCourse2(i);
			   clearTimeout(FreeCourseTime);
			   }
		)
		$(this).mousemove(function(e){
			xx=e.pageX;
			$('.FreeCourseLayer').eq(i).css('left',xx-206);
		})
		})	
	//--
	$('.btn1').hover(
	   function(){
		   $(this).addClass('btn1Now');
		   },
	   function(){
		   $(this).removeClass('btn1Now');
		   }
	)
	$('.btn2').hover(
	   function(){
		   $(this).addClass('btn1Now');
		   },
	   function(){
		   $(this).removeClass('btn1Now');
		   }
	)
	$('.btnDiv').find('input').hover(
	   function(){
		   $(this).addClass('btn1Now');
		   },
	   function(){
		   $(this).removeClass('btn1Now');
		   }
	)
	//--
	$('.timeLayerA').hover(
	   function(){
		   $('.timeLayer').css('top',$(this).offset().top+5);
		   $('.timeLayer').show();
		   },
	   function(){
		   $('.timeLayer').hide();
		   }
	)	
	$('.timeLayer').hover(
	   function(){
		   $(this).show();
		   },
	   function(){
		   $(this).hide();
		   }
	)
	//--
	$('.sellerPart2Btn').click(function(){
		$('.sellerPart2Layer').css('left',$(this).offset().left-330);
		$('.sellerPart2Layer').css('top',$(this).offset().top+20);
		$('.sellerPart2Layer').show();
		})
	//--
	$('.dateLayer11').find('li').find('span').click(function(){
		if($(this).attr('class')=="spanNow"){
			$(this).removeClass('spanNow');
			}else{
				$(this).addClass('spanNow');
				}
		})
	$('.dateLayer11').hover(
	   function(){},
	   function(){
		   $('.dateLayer11').hide();
		   }
	)				
	//
	})